### ISSUE TITLE
Cannot always check / uncheck tracks

### ISSUE THREAD

**Issue by messman** [anorthrup0325/spotify-playlist-updater#1]
When using the Update Playlist Modal, sometimes I can't check/uncheck tracks.
It seems different each time I open the modal. The first time, I could only uncheck the third track but not any others. The second time, I couldn't uncheck any of the checkboxes I tried. 

My case: public album of Shania Twain, 7 songs in the playlist to begin with, running the tool found 181 new tracks.

**Comment by anthonynorthrup314** [comment]
This should be resolved now :) Let me know if it's still open @messman
